import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "TodoList",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-4 py-2.5`}>
        <Navbar />
        {children}</body>
    </html>
  );
}
